### ISSUE TITLE
如何批量修改mysql的某个字段值

### ISSUE THREAD

**Issue by flik1337** [lcctoor/arts#4]
非常感谢开源了这个很方便的mysql工具，但文档部分还需要进一步完善。

关于如何批量修改某个字段的值，文档中这部分描述的不太清晰。

例如，我需要将查询结果中的`summary`字段的值，修改为经过`removeHtmlParse`方法处理的值。
根据文档中的描述，我只能通过下面这种非常笨拙的方式实现。

r = sheet[mc.summary.re('class="intro"')][:]

for row in r:
    summary = removeHtmlParse(row['summary'])
    sheet[mc.id == row['id']][:] = {
            'summary': summary
    }

请问如何更好地实现。

**Comment by canbiaoxu** [comment]
你好，我认为你的提案很有建设性，我将开始更新源码。在此之前，你可以先按以下的方式：

```python
for x in sheet[mc.summary.re('class="intro"')]['id', 'summary'][:]:
    sheet[mc.id == x['id']][1] = {'summary': removeHtmlParse(x['summary'])}
```

解释：['id', 'summary']表示只提取这两个字段，这样可以提高性能。

**Comment by flik1337** [comment]
好的，非常感谢 :)

**Comment by canbiaoxu** [comment]
功能已实现，请更新coolmysql包到1.4版本。
```
pip install --upgrade coolmysql>=1.4
```

### apply-用自定义函数修改

```python
def edit_line(line:dict):
    line['年龄'] += 1  # 年龄统一加1岁
    if line['年龄'] > 13:
        line['爱好'] = '足球'
    else:
        line['爱好'] = '篮球'
    line['姓名'] = line['姓名'].replace('小', 'xiao')

sheet[mc.年龄>11].apply(edit_line)[:]  # 修改所有数据
sheet[mc.年龄>11].apply(edit_line)[2:-2]  # 修改第2~倒数第2条
sheet[mc.年龄>11].apply(edit_line)[2]  # 修改第2条数据
```

注意：

该函数接收且仅接收1个参数，参数名可以不是‘line’。

**Comment by flik1337** [comment]
执行以下语句，报错：
`    r = sheet[mc.author != ""].apply(clean_book)[1:10]`
错误如下：
```
Traceback (most recent call last):
  File "/Users/flik/workspace/python_ws/douban_scrapy/douban/clean/douban_read_clean.py", line 167, in <module>
    r = sheet[mc.author != ""].apply(clean_book)[1:10]
  File "/Users/flik/opt/anaconda3/envs/douban/lib/python3.9/site-packages/lccpy/coolmysql/_coolmysql.py", line 243, in __getitem__
    return self.func(key, *self.vs, **self.kvs)
  File "/Users/flik/opt/anaconda3/envs/douban/lib/python3.9/site-packages/lccpy/coolmysql/_coolmysql.py", line 294, in _applyBase
    pk = self.getPK()
  File "/Users/flik/opt/anaconda3/envs/douban/lib/python3.9/site-packages/lccpy/coolmysql/_coolmysql.py", line 459, in getPK
    object.__setattr__(self, '_pk', rdata[0]['COLUMN_NAME'])
KeyError: 'COLUMN_NAME'
```

**Comment by lcctoor** [comment]
好的，我下班后看看

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by canbiaoxu** [comment]
在获取主键时出问题，请你在Navicat上执行一下以下SQL代码，看看返回什么：

```python
dbName = ''
sheetName = ''
sql = f"select column_name from information_schema.columns where table_schema = '{dbName}' and table_name = '{sheetName}' and column_key='PRI' "
```

**Comment by flik1337** [comment]
返回的值为：column:id
<img width="165" alt="image" src="https://user-images.githubusercontent.com/56709053/232748905-5a7540d2-5f77-492d-950f-7c365a8fd5fa.png">

**Comment by lcctoor** [comment]
我明白问题出在哪了：不同版本的MySQL返回的字段大小写不一样，我脚本里写的是'COLUMN_NAME'，你的MySQL版本返回的是‘column_name’，小问题，稍晚一点我更新一下代码。

**Comment by canbiaoxu** [comment]
谢谢你的反馈，问题已修复，请更新coolmysql包到1.4.2版本。
```
pip install --upgrade coolmysql>=1.4.2
```
